#!/bin/bash
#SBATCH --partition=rome
#SBATCH --job-name=bm25
#SBATCH --time=24:00:00
#SBATCH --output=./slurm_out/bm25_%j.out
#SBATCH --mem=128G

set -e

# Activate your environment if needed:
# source venv/bin/activate
module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0/
module load Java/21.0.2

source activate bm25

echo "Running BM25 evaluations with PyTerrier..."

python eval_bm25.py
