#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=beir_bert_cased_lower
#SBATCH --time=3:00:00
#SBATCH --output=./slurm_out/beir/bert_cased_lower_%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0/
module load Java/21.0.2

source activate splade

conda activate splade

export PYTHONPATH=$PYTHONPATH:$(pwd)
export SPLADE_CONFIG_NAME="bert_cased_lower_nochange.yaml"
for dataset in arguana fiqa nfcorpus quora trec-covid webis-touche2020 dbpedia-entity fever hotpotqa nq scidocs scifact climate-fever
do
  python3 -m splade.beir_eval \
    +beir.dataset=$dataset \
    +beir.dataset_path=data/beir
done
