#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=all_splade
#SBATCH --time=3:00:00
#SBATCH --output=./slurm_out/beir/distil_uncased_%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0/
module load Java/21.0.2

source activate splade

export PYTHONPATH=$PYTHONPATH:$(pwd)
export SPLADE_CONFIG_NAME="config_splade++_msedistil.yaml"
for dataset in scidocs scifact trec-covid webis-touche2020 climate-fever dbpedia-entity fever hotpotqa nq
do
  python3 -m splade.beir_eval \
    +beir.dataset=$dataset \
    +beir.dataset_path=data/beir \
    config.index_retrieve_batch_size=100 \
    config.checkpoint_dir=experiments/splade/checkpoint \
    config.index_dir=experiments/splade/index \
    config.out_dir=experiments/splade/out
done
