#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=2
#SBATCH --job-name=bert_cased_nochange_uncased
#SBATCH --time=24:00:00
#SBATCH --output=./slurm_out/train/bert_cased_nochange_uncased_%j.out

#exit if an error occurs
set -e

module purge
module load 2024
module load Miniconda3/24.7.1-0
module load CUDA/12.6.0/
module load Java/21.0.2

source activate splade
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:128

export PYTHONPATH=$PYTHONPATH:$(pwd)
export SPLADE_CONFIG_NAME="bert_cased_nochange_uncased.yaml"
python3 -m splade.all